spring.config.import=optional:file:.env.properties
spring.datasource.url=${DB_3D_URL}
spring.datasource.username=${DB_3D_USER}
spring.datasource.password=${DB_3D_PASSWORD}

spring.liquibase.parameters.restaurant.owner.id1=${OWNER_ID1}
spring.liquibase.parameters.restaurant.id1=${RESTAURANT1}
spring.liquibase.parameters.restaurant.id2=${RESTAURANT2}
spring.liquibase.parameters.category.id1=${Italian}
spring.liquibase.parameters.category.id2=${Chinese}
spring.liquibase.parameters.category.id3=${Japanese}
spring.liquibase.parameters.category.id4=${French}
spring.liquibase.parameters.dish.id1=${Doria}
spring.liquibase.parameters.dish.id2=${Pasta}
spring.liquibase.parameters.allergy.id1=${Shrimp}
spring.liquibase.parameters.allergy.id2=${EGG}

jwt.access.expiration=3600000
jwt.refresh.expiration=604800000
JWT_SECRET=${JWT_SECRET}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
