spring.application.name=backend
spring.profiles.active=dev
# False to check startup
spring.liquibase.enabled=false
spring.liquibase.change-log=classpath:/db/changelog/changelog-master.yaml
spring.datasource.driver-class-name=org.postgresql.Driver
