spring.application.name=backend
spring.profiles.active=dev
# False to check startup
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/changelog-master.yaml
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=${DB_3D_URL}
spring.datasource.username=${DB_3D_USER}
spring.datasource.password=${DB_3D_PASSWORD}

jwt.access.expiration=3600000
jwt.refresh.expiration=604800000
JWT_SECRET=${JWT_SECRET}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

cloud.aws.credentials.accessKey=${AWS_ACCESS_KEY}
cloud.aws.credentials.secretKey=${AWS_SECRET_KEY}
cloud.aws.region.static=${AWS_REGION}
cloud.aws.s3.bucket=${AWS_S3_BUCKET}
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB

