spring.config.import=optional:file:.env.properties
spring.datasource.url=${DB_3D_URL}
spring.datasource.username=${DB_3D_USER}
spring.datasource.password=${DB_3D_PASSWORD}
spring.liquibase.change-log=classpath:/db/changelog/dev/changelog-master-dev.yaml
spring.liquibase.parameters.restaurant.owner.id1=e7d8c864-ff83-442f-96f3-e8a2021672a7
spring.liquibase.parameters.restaurant.owner.id2=4942a9c7-d55a-418f-bd1e-6b1fa727db88

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
